### ISSUE TITLE
I think you should more clearly show what each of the values mean

### ISSUE THREAD

**Issue by nikivdev** [therockmandolinist/alfred-atmos#1]
For example : 

![2016-07-30 at 17 43](https://cloud.githubusercontent.com/assets/6391776/17271476/1dcc77c4-567d-11e6-8449-bbd436c287b7.png)

I really don't know what all these values actually give me. Which on is sound, pressure, and density at queried altitude?

Perhaps add 'atmos help' which shows what each symbol stands for. What do you think?

**Comment by dieggsy** [comment]
Oh, well thanks for taking a look! I'd say three of the symbols are fairly common for what they stand for, (`T` for temperature, `P` for pressure, `rho` for density). Perhaps `a` as the speed of sound is a bit more ambiguous. 

I'll think about it though. In any case, it's based pretty directly on [atmosisa](http://www.mathworks.com/help/aerotbx/ug/atmosisa.html), though now that you mention it perhaps I should be more clear about the units as well... maybe that would help clear up the ambiguity?

**Comment by nikivdev** [comment]
I would probably name them (T)temperature, (P)pressure, (D)entity, Speed of (L)ight and add a little description in the workflow itself. Thanks for sharing the workflow though.

**Comment by dieggsy** [comment]
Thanks for checking it out! I'm gonna try and make this a little clearer (units, description), per your suggestions.

**Comment by dieggsy** [comment]
I've added units and an 'atmoshelp' command. Thanks for the suggestion :)
